export type IconLibrary = {
  name: string
  slug: string
  description: string
  website: string
  github: string
  npm: string
  stars: number
  iconCount: number
  license: string
  frameworks: string[]
  style: string[]
  figmaPlugin: boolean
  typescript: boolean
  treeshakable: boolean
  pros: string[]
  cons: string[]
  installCommand: string
  usageExample: string
}

export const icons: IconLibrary[] = [
  {
    name: "Lucide Icons",
    slug: "lucide-icons",
    description: "A clean, consistent open-source icon library with 1960+ icons, forked from Feather Icons with active maintenance and TypeScript support.",
    website: "https://lucide.dev",
    github: "https://github.com/lucide-icons/lucide",
    npm: "lucide-react",
    stars: 12000,
    iconCount: 1960,
    license: "ISC",
    frameworks: ["react", "vue", "svelte", "nextjs"],
    style: ["outline"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["Actively maintained", "Consistent style", "TypeScript support", "Tree-shakable"],
    cons: ["Outline only", "No filled variant"],
    installCommand: "npm install lucide-react",
    usageExample: "import { Home } from 'lucide-react'\n\nexport default function App() {\n  return <Home size={24} />\n}"
  },
  {
    name: "Heroicons",
    slug: "heroicons",
    description: "Beautiful hand-crafted SVG icons by the makers of Tailwind CSS. Available in outline and solid styles with 324 icons.",
    website: "https://heroicons.com",
    github: "https://github.com/tailwindlabs/heroicons",
    npm: "@heroicons/react",
    stars: 21000,
    iconCount: 324,
    license: "MIT",
    frameworks: ["react", "vue", "nextjs"],
    style: ["outline", "solid", "mini"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["Made by Tailwind team", "Multiple styles", "High quality"],
    cons: ["Only 292 icons", "Limited framework support"],
    installCommand: "npm install @heroicons/react",
    usageExample: "import { HomeIcon } from '@heroicons/react/24/outline'\n\nexport default function App() {\n  return <HomeIcon className='h-6 w-6' />\n}"
  },
  {
    name: "Tabler Icons",
    slug: "tabler-icons",
    description: "Over 6100 free MIT-licensed high-quality SVG icons. One of the largest free icon libraries available for web projects.",
    website: "https://tabler-icons.io",
    github: "https://github.com/tabler/tabler-icons",
    npm: "@tabler/icons-react",
    stars: 18000,
    iconCount: 6147,
    license: "MIT",
    frameworks: ["react", "vue", "svelte", "nextjs"],
    style: ["outline", "filled"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["Largest collection", "Both outline and filled", "Very consistent"],
    cons: ["Large package if not tree-shaken"],
    installCommand: "npm install @tabler/icons-react",
    usageExample: "import { IconHome } from '@tabler/icons-react'\n\nexport default function App() {\n  return <IconHome size={24} />\n}"
  },
  {
    name: "Phosphor Icons",
    slug: "phosphor-icons",
    description: "Flexible icon family with 6 weights including thin, light, regular, bold, fill and duotone. Over 1500 icons available.",
    website: "https://phosphoricons.com",
    github: "https://github.com/phosphor-icons/react",
    npm: "@phosphor-icons/react",
    stars: 8000,
    iconCount: 1533,
    license: "MIT",
    frameworks: ["react", "vue", "nextjs"],
    style: ["thin", "light", "regular", "bold", "fill", "duotone"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["6 weight variants", "Duotone support", "Large collection"],
    cons: ["Heavier package size"],
    installCommand: "npm install @phosphor-icons/react",
    usageExample: "import { House } from '@phosphor-icons/react'\n\nexport default function App() {\n  return <House size={24} weight='duotone' />\n}"
  },
  {
    name: "Remix Icon",
    slug: "remix-icon",
    description: "Open-source neutral-style system symbols for designers and developers. Over 3200 icons in line and fill styles.",
    website: "https://remixicon.com",
    github: "https://github.com/Remix-Design/RemixIcon",
    npm: "remixicon",
    stars: 6000,
    iconCount: 3229,
    license: "Apache 2.0",
    frameworks: ["react", "vue", "nextjs"],
    style: ["line", "fill"],
    figmaPlugin: false,
    typescript: false,
    treeshakable: false,
    pros: ["2800+ icons", "Both line and fill", "Free for commercial use"],
    cons: ["No TypeScript", "Not tree-shakable"],
    installCommand: "npm install remixicon",
    usageExample: "import 'remixicon/fonts/remixicon.css'\n\nexport default function App() {\n  return <i className='ri-home-line'></i>\n}"
  },
  {
    name: "Feather Icons",
    slug: "feather-icons",
    description: "Simply beautiful open source icons designed on a 24x24 grid with an emphasis on simplicity, consistency and readability.",
    website: "https://feathericons.com",
    github: "https://github.com/feathericons/feather",
    npm: "react-feather",
    stars: 24000,
    iconCount: 287,
    license: "MIT",
    frameworks: ["react", "nextjs"],
    style: ["outline"],
    figmaPlugin: false,
    typescript: false,
    treeshakable: true,
    pros: ["Minimal and clean", "Lightweight", "High GitHub stars"],
    cons: ["No longer maintained", "Only 287 icons", "No TypeScript"],
    installCommand: "npm install react-feather",
    usageExample: "import { Home } from 'react-feather'\n\nexport default function App() {\n  return <Home size={24} />\n}"
  },
  {
    name: "Bootstrap Icons",
    slug: "bootstrap-icons",
    description: "Free, high quality, open source icon library with over 2000 icons. Designed by the Bootstrap team.",
    website: "https://icons.getbootstrap.com",
    github: "https://github.com/twbs/icons",
    npm: "bootstrap-icons",
    stars: 7000,
    iconCount: 2078,
    license: "MIT",
    frameworks: ["react", "vue", "nextjs"],
    style: ["outline", "filled"],
    figmaPlugin: true,
    typescript: false,
    treeshakable: false,
    pros: ["1800+ icons", "Both styles", "Backed by Bootstrap team"],
    cons: ["No TypeScript", "Not tree-shakable"],
    installCommand: "npm install bootstrap-icons",
    usageExample: "import 'bootstrap-icons/font/bootstrap-icons.css'\n\nexport default function App() {\n  return <i className='bi bi-house'></i>\n}"
  },
  {
    name: "Radix Icons",
    slug: "radix-icons",
    description: "A crisp set of 15x15 icons designed by the WorkOS team. Perfectly sized for dense UIs and dashboards.",
    website: "https://radix-ui.com/icons",
    github: "https://github.com/radix-ui/icons",
    npm: "@radix-ui/react-icons",
    stars: 5000,
    iconCount: 318,
    license: "MIT",
    frameworks: ["react", "nextjs"],
    style: ["outline"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["Perfect for dense UIs", "TypeScript support", "Made by Radix team"],
    cons: ["Only 318 icons", "15x15 fixed size only"],
    installCommand: "npm install @radix-ui/react-icons",
    usageExample: "import { HomeIcon } from '@radix-ui/react-icons'\n\nexport default function App() {\n  return <HomeIcon />\n}"
  },


  {
    name: 'React Icons',
    slug: 'react-icons',
    description: 'One package, 52,000+ icons. Aggregates Font Awesome, Material Design, Heroicons, Tabler, Feather, Bootstrap Icons, and 20+ more icon sets under a single unified React API.',
    website: 'https://react-icons.github.io/react-icons/',
    github: 'https://github.com/react-icons/react-icons',
    npm: 'react-icons',
    stars: 11500,
    iconCount: 52000,
    license: 'MIT',
    frameworks: ['react', 'nextjs'],
    style: ['outline', 'filled', 'duotone', 'brands'],
    figmaPlugin: false,
    typescript: true,
    treeshakable: true,
    pros: [
      'One package replaces 25+ separate installs',
      '40,000+ icons — largest vocabulary available',
      'Unified API across all included sets',
      'Full TypeScript support',
    ],
    cons: [
      'No consistent visual identity — mixing sets looks inconsistent',
      'Heavy node_modules footprint',
      'Not a library — a wrapper around other libraries',
    ],
    installCommand: 'npm install react-icons',
    usageExample: "import { FaHome } from 'react-icons/fa'\nimport { MdSettings } from 'react-icons/md'\nimport { HiUser } from 'react-icons/hi'\n\nexport default function App() {\n  return (\n    <div>\n      <FaHome size={24} />\n      <MdSettings size={24} />\n      <HiUser size={24} />\n    </div>\n  )\n}",
  },

  {
    name: 'Material Icons',
    slug: 'material-icons',
    description: "Google's official Material Design icon library for React. 2,100+ icons across 5 styles — Filled, Outlined, Rounded, Sharp, and TwoTone. The most downloaded React icon package with 5.1M weekly npm installs. Requires @mui/material as a peer dependency.",
    website: 'https://mui.com/material-ui/material-icons/',
    github: 'https://github.com/mui/material-ui/tree/master/packages/mui-icons-material',
    npm: '@mui/icons-material',
    stars: 98300,
    iconCount: 2100,
    license: 'MIT',
    frameworks: ['react', 'nextjs'],
    style: ['filled', 'outlined', 'rounded', 'sharp', 'twotone'],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: [
      '5 style variants per icon — Filled, Outlined, Rounded, Sharp, TwoTone from one package',
      'Most downloaded React icon package — 5.1M weekly npm installs, 98K GitHub stars',
      'Native MUI integration — sx prop, theme color tokens, fontSize scale all work out of the box',
      "Google's official Material Design visual language — recognized by billions of Android and web users",
      'Works in Next.js Server Components — renders static SVG HTML with no use client required',
      'Full TypeScript support — SvgIconProps type covers sx, color, fontSize, and className',
    ],
    cons: [
      'Requires 3 peer dependencies — @mui/material, @emotion/styled, @emotion/react (~300KB gzip if not on MUI)',
      'Named barrel imports are up to 6x slower in Vite/webpack dev mode — path imports required',
      'React only — no official Vue, Svelte, or vanilla JS packages',
      'Material Design aesthetic reads as Google/Android — not ideal for minimal modern SaaS UIs',
      'No stroke width customization — must switch variants to change visual weight',
      'Material Symbols (the successor) is not yet supported by @mui/icons-material',
    ],
    installCommand: 'npm install @mui/icons-material @mui/material @emotion/styled @emotion/react',
    usageExample: "import HomeIcon from '@mui/icons-material/Home'\nimport HomeOutlinedIcon from '@mui/icons-material/HomeOutlined'\nimport SearchIcon from '@mui/icons-material/Search'\nimport DeleteIcon from '@mui/icons-material/Delete'\n\n// ✅ Path imports — up to 6x faster in dev than barrel imports\n// ❌ Avoid: import { HomeIcon } from '@mui/icons-material'\n\nexport default function App() {\n  return (\n    <div>\n      {/* Filled — bold, solid, for primary actions */}\n      <HomeIcon />\n\n      {/* Outlined — minimal stroke-style, for supporting UI */}\n      <HomeOutlinedIcon />\n\n      {/* Sizing via fontSize prop */}\n      <SearchIcon fontSize=\"small\" />   {/* 20px */}\n      <SearchIcon fontSize=\"medium\" />  {/* 24px default */}\n      <SearchIcon fontSize=\"large\" />   {/* 35px */}\n      <SearchIcon sx={{ fontSize: 48 }} />\n\n      {/* Color via MUI theme tokens or custom hex */}\n      <DeleteIcon color=\"error\" />\n      <DeleteIcon sx={{ color: '#6366f1' }} />\n    </div>\n  )\n}",
  },

  // ── Iconify ───────────────────────────────────────────────────────────────────


// ── Simple Icons ──────────────────────────────────────────────────────────────
  {
    name: 'Simple Icons',
    slug: 'simple-icons',
    description: '3,200 free SVG brand icons for every major technology company, social platform, and developer tool. GitHub, Stripe, Vercel, AWS, Figma, Linear, and thousands more. CC0 public domain — no attribution required. The largest free brand icon library available, with 25K GitHub stars and official brand colors included for every icon.',
    website: 'https://simpleicons.org',
    github: 'https://github.com/simple-icons/simple-icons',
    npm: '@icons-pack/react-simple-icons',
    stars: 25047,
    iconCount: 3200,
    license: 'CC0 1.0 (Public Domain)',
    frameworks: ['react', 'nextjs'],
    style: ['filled'],
    figmaPlugin: false,
    typescript: true,
    treeshakable: true,
    pros: [
      '3,109 brand icons — 6x more than Font Awesome Brands (465) at zero cost',
      'CC0 public domain — no attribution required, no license notices, use in any commercial project',
      'Official brand hex colors included — render SiStripe in #635BFF, SiGithub in #181717 with one prop',
      'Works in Next.js Server Components — renders static SVG HTML with no use client required',
      'Full TypeScript support — all 3,109 Si-prefixed components are typed with full VS Code autocomplete',
      'Actively maintained — new brand icons added regularly, existing icons updated on rebrands',
    ],
    cons: [
      'Brand icons only — no UI icons whatsoever, must pair with Lucide or Heroicons for product UI',
      'Monochromatic only — all icons are single-fill SVG, no multi-color logos (Google, Mastercard)',
      'React package (@icons-pack/react-simple-icons) is community-maintained, not by Simple Icons org',
      'CC0 covers the SVG file, not trademark rights — brand logos remain trademarks of their owners',
      'No Vue, Svelte or vanilla package — use core simple-icons package with manual SVG rendering',
    ],
    installCommand: 'npm install @icons-pack/react-simple-icons',
    usageExample: "import {\n  SiGithub,\n  SiVercel,\n  SiStripe,\n  SiReact,\n  SiNextdotjs,\n  SiTailwindcss,\n} from '@icons-pack/react-simple-icons'\n// All components use 'Si' prefix + PascalCase brand name\n\nexport function TechStack() {\n  return (\n    <div className=\"flex items-center gap-4\">\n      {/* Use currentColor — inherits from parent */}\n      <SiGithub size={24} />\n      <SiVercel size={24} />\n\n      {/* Use official brand color */}\n      <SiStripe size={24} color=\"#635BFF\" />\n      <SiReact size={24} color=\"#61DAFB\" />\n\n      {/* Social links row */}\n      <a href=\"https://github.com\" aria-label=\"GitHub\">\n        <SiGithub size={20} className=\"text-gray-600 hover:text-gray-900\" />\n      </a>\n    </div>\n  )\n}",
  },
  
  // ── Iconoir ──────────────────────────────────────────────────────────────────
  {
    name: 'Iconoir',
    slug: 'iconoir',
    description: 'A high-quality, open-source icon library featuring over 1,300 meticulously crafted line icons. Highly consistent, premium aesthetic perfect for modern UIs.',
    website: 'https://iconoir.com',
    github: 'https://github.com/iconoir-icons/iconoir',
    npm: 'iconoir-react',
    stars: 5200,
    iconCount: 1384,
    license: 'MIT',
    frameworks: ['react', 'nextjs', 'vue', 'solid'],
    style: ['outline'],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: [
      'Incredibly consistent, premium aesthetic that rivals paid libraries.',
      'Wide framework support including React Native and Flutter.',
      'Highly customizable stroke widths.',
      'Excellent Figma plugin synchronization.'
    ],
    cons: [
      'Line style only — no filled or duotone variants.',
      'Does not include brand/social media icons.'
    ],
    installCommand: 'npm install iconoir-react',
    usageExample: "import { Camera, Search } from 'iconoir-react'\n\nexport default function App() {\n  return (\n    <div className=\"flex gap-4 text-blue-500\">\n      <Camera color=\"currentColor\" strokeWidth={1.5} />\n      <Search />\n    </div>\n  )\n}",
  },
  {
    name: "IonIcons",
    slug: "ionicons",
    description: "Premium, carefully designed icons by the Ionic Framework team. Provides Outline, Filled, and Sharp variants with over 1300 icons for responsive mobile and web apps.",
    website: "https://ionic.io/ionicons",
    github: "https://github.com/ionic-team/ionicons",
    npm: "react-ionicons",
    stars: 17200,
    iconCount: 1300,
    license: "MIT",
    frameworks: ["react", "nextjs", "vanilla"],
    style: ["outline", "filled", "sharp"],
    figmaPlugin: false,
    typescript: true,
    treeshakable: true,
    pros: [
      "Outline, Filled, and Sharp variants for every single icon",
      "Designed specifically for high-fidelity iOS and Android web applications",
      "Robust official react-ionicons NPM module for quick React integration",
      "Clean path dimensions optimized for small layouts (16px/24px)",
    ],
    cons: [
      "No official bindings for Vue or Svelte",
      "NPM library uses string size props instead of standard numbers",
    ],
    installCommand: "npm install react-ionicons",
    usageExample: "import { HomeOutline } from 'react-ionicons'\n\nexport default function App() {\n  return <HomeOutline color='#6366f1' height='24px' width='24px' />\n}"
  },
  {
    name: "Octicons",
    slug: "octicons",
    description: "GitHub's official icon set designed specifically for developer dashboards, code repositories, git histories, and developer utilities.",
    website: "https://primer.style/octicons/",
    github: "https://github.com/primer/octicons",
    npm: "@primer/octicons-react",
    stars: 10400,
    iconCount: 280,
    license: "MIT",
    frameworks: ["react", "vue", "nextjs", "jekyll"],
    style: ["outline"],
    figmaPlugin: false,
    typescript: true,
    treeshakable: true,
    pros: [
      "Designed on strict 16px and 24px grid systems to prevent rendering blurriness",
      "Specialized Git workflow, repo, pull-request, and codebase symbols",
      "Maintained directly by GitHub's design systems team",
      "Built-in semantic accessibility descriptions and aria attributes",
    ],
    cons: [
      "Small overall collection size (280 icons)",
      "Strictly technical visual aesthetic, no multitone or colored variations",
    ],
    installCommand: "npm install @primer/octicons-react",
    usageExample: "import { RepoIcon } from '@primer/octicons-react'\n\nexport default function App() {\n  return <RepoIcon size={16} />\n}"
  },
  {
    name: "Ant Design Icons",
    slug: "ant-design-icons",
    description: "The official icon set for Ant Design (AntD), featuring over 800 highly consistent icons in Outlined, Filled, and TwoTone themes for enterprise UIs.",
    website: "https://ant.design/components/icon",
    github: "https://github.com/ant-design/ant-design-icons",
    npm: "@ant-design/icons",
    stars: 8700,
    iconCount: 840,
    license: "MIT",
    frameworks: ["react", "vue"],
    style: ["outline", "filled", "twotone"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["Three distinct themes", "Native React components", "Dynamic TwoTone coloring", "Enterprise grade"],
    cons: ["Opinionated aesthetic", "No mini variants", "Relies on CSS font-size for scaling"],
    installCommand: "npm install @ant-design/icons",
    usageExample: "import { SmileTwoTone } from '@ant-design/icons'\n\nexport default function App() {\n  return <SmileTwoTone twoToneColor='#eb2f96' style={{ fontSize: '24px' }} />\n}"
  },
  {
    name: "Mage Icons",
    slug: "iconify-mage",
    description: "A beautifully clean, pixel-perfect icon set designed for modern web products. Features highly consistent vector symbols in outline and solid styles.",
    website: "https://mageicons.com",
    github: "https://github.com/mageicons/mage-icons",
    npm: "@mageicons/react",
    stars: 320,
    iconCount: 1042,
    license: "MIT",
    frameworks: ["react", "nextjs"],
    style: ["outline", "filled"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["Extremely modern look", "Very clean paths", "Highly consistent stroke weight"],
    cons: ["Smaller library size than Tabler or Phosphor"],
    installCommand: "npm install @mageicons/react",
    usageExample: "import { Home } from '@mageicons/react'\n\nexport default function App() {\n  return <Home size={24} />\n}"
  },
  {
    name: "Line Awesome",
    slug: "iconify-la",
    description: "A modern, lightweight outline icon set designed to replace Font Awesome with clean, outline-based web icons.",
    website: "https://icons8.com/line-awesome",
    github: "https://github.com/icons8/line-awesome",
    npm: "line-awesome",
    stars: 2100,
    iconCount: 1554,
    license: "MIT",
    frameworks: ["react", "nextjs"],
    style: ["outline"],
    figmaPlugin: true,
    typescript: false,
    treeshakable: false,
    pros: ["Drop-in replacement for Font Awesome", "Beautiful outline weight", "Extremely recognizable shapes"],
    cons: ["Mainly designed as a font package", "No native treeshakable React build"],
    installCommand: "npm install line-awesome",
    usageExample: "import 'line-awesome/dist/line-awesome/css/line-awesome.min.css'\n\nexport default function App() {\n  return <i className='la la-home'></i>\n}"
  },
  {
    name: "Solar Icons",
    slug: "iconify-solar",
    description: "An incredibly beautiful, modern, multi-style icon library featuring outline, linear, bold, broken, and duotone weights.",
    website: "https://solaricons.com",
    github: "https://github.com/480-design/solar-icons",
    npm: "solar-icon-set",
    stars: 450,
    iconCount: 7400,
    license: "MIT",
    frameworks: ["react", "vue", "nextjs"],
    style: ["outline", "linear", "bold", "broken", "duotone"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["Incredible variety of styles", "Modern broken-line styling option", "Over 7,000 icons"],
    cons: ["Heavier library to load fully"],
    installCommand: "npm install solar-icon-set",
    usageExample: "import { Home } from 'solar-icon-set'\n\nexport default function App() {\n  return <Home size={24} />\n}"
  },
  {
    name: "Fluent UI Icons",
    slug: "iconify-fluent",
    description: "Microsoft's official Fluent Design System icon set, featuring clean outline and filled variants optimized for modern product design.",
    website: "https://fluenticons.co",
    github: "https://github.com/microsoft/fluentui-system-icons",
    npm: "@fluentui/react-icons",
    stars: 3200,
    iconCount: 4000,
    license: "MIT",
    frameworks: ["react", "nextjs"],
    style: ["outline", "filled"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["Backed by Microsoft design", "Enterprise grade consistency", "Massive count"],
    cons: ["Strongly aligned with Microsoft design guidelines"],
    installCommand: "npm install @fluentui/react-icons",
    usageExample: "import { Home24Regular } from '@fluentui/react-icons'\n\nexport default function App() {\n  return <Home24Regular />\n}"
  },
  {
    name: "Carbon Icons",
    slug: "iconify-carbon",
    description: "IBM's official open-source design system icon set, optimized for high-density corporate dashboards and technical UIs.",
    website: "https://carbondesignsystem.com",
    github: "https://github.com/carbon-design-system/carbon",
    npm: "@carbon/icons-react",
    stars: 8500,
    iconCount: 2000,
    license: "Apache 2.0",
    frameworks: ["react", "vue", "svelte", "nextjs"],
    style: ["outline"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["Designed for technical enterprise layouts", "Crisp grid alignment", "Excellent accessibility"],
    cons: ["Very formal/industrial aesthetic"],
    installCommand: "npm install @carbon/icons-react",
    usageExample: "import { Home } from '@carbon/icons-react'\n\nexport default function App() {\n  return <Home size={24} />\n}"
  },
  {
    name: "Material Symbols",
    slug: "iconify-material-symbols",
    description: "Google's newest variable icon set, consolidating outline, filled, rounded, and sharp options in one flexible engine.",
    website: "https://fonts.google.com/icons",
    github: "https://github.com/google/material-design-icons",
    npm: "@material-symbols/svg-600",
    stars: 49000,
    iconCount: 3000,
    license: "Apache 2.0",
    frameworks: ["react", "nextjs", "vanilla"],
    style: ["outline", "filled", "rounded", "sharp"],
    figmaPlugin: true,
    typescript: true,
    treeshakable: true,
    pros: ["Highly customizable variables", "Official modern Google symbols set", "Extremely familiar to Android users"],
    cons: ["Variable font integration is slow in dev mode"],
    installCommand: "npm install @material-symbols/svg-600",
    usageExample: "import Home from '@material-symbols/svg-600/Home.svg'\n\nexport default function App() {\n  return <img src={Home} />\n}"
  },
  {
    name: "BoxIcons",
    slug: "iconify-bi",
    description: "A simple, clean open-source vector icon set designed for web layouts and web development.",
    website: "https://boxicons.com",
    github: "https://github.com/atisawd/boxicons",
    npm: "boxicons",
    stars: 1700,
    iconCount: 1600,
    license: "CC BY 4.0",
    frameworks: ["react", "nextjs"],
    style: ["outline", "filled", "logos"],
    figmaPlugin: true,
    typescript: false,
    treeshakable: false,
    pros: ["Over 1,500 icons", "Includes popular social/brand logos", "Very clean outline designs"],
    cons: ["No longer updated frequently", "No native TypeScript definitions"],
    installCommand: "npm install boxicons",
    usageExample: "import 'boxicons/css/boxicons.min.css'\n\nexport default function App() {\n  return <i className='bx bx-home'></i>\n}"
  },
  {
    name: "Devicons",
    slug: "devicons",
    description: "800+ developer and technology brand icons — logos for every programming language, framework, database, and tool. Available in original (color), plain, and line variants.",
    website: "https://devicon.dev",
    github: "https://github.com/devicons/devicon",
    npm: "devicon",
    stars: 9500,
    iconCount: 800,
    license: "MIT",
    frameworks: ["react", "vue", "svelte", "nextjs", "vanilla"],
    style: ["original", "plain", "line", "wordmark"],
    figmaPlugin: false,
    typescript: false,
    treeshakable: false,
    pros: ["800+ technology logos", "Multiple color variants", "CDN-ready with zero install", "Actively maintained"],
    cons: ["Technology logos only — no UI icons", "No official React component package", "Font loads all icons"],
    installCommand: '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />',
    usageExample: "<!-- Font class usage -->\n<i class=\"devicon-react-original colored\"></i>\n<i class=\"devicon-typescript-plain colored\"></i>\n\n<!-- SVG usage -->\n<img src=\"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg\" width=\"24\" />"
  },
  {
    name: "Teenyicons",
    slug: "teenyicons",
    description: "Tiny, minimalist 1px-stroke vector icons designed to fit beautifully in the smallest spaces. Optimised for 15x15 grids.",
    website: "https://teenyicons.com",
    github: "https://github.com/teenyicons/teenyicons",
    npm: "teenyicons",
    stars: 2100,
    iconCount: 1200,
    license: "MIT",
    frameworks: ["react", "vue", "svelte", "nextjs", "vanilla"],
    style: ["outline", "solid"],
    figmaPlugin: true,
    typescript: false,
    treeshakable: true,
    pros: ["Superb pixel sharpness at tiny sizes", "Consistent 1px line thickness", "Outline and Solid visual match"],
    cons: ["Very basic/geometric look", "No official custom wrapper modules"],
    installCommand: "npm install teenyicons",
    usageExample: "import { Home } from 'teenyicons'\n\nexport default function App() {\n  return <Home className='w-4 h-4' />\n}"
  },
  {
    name: "Circum Icons",
    slug: "circum-icons",
    description: "Consistent, ultra-minimalist line icons featuring simple visual geometry and rounded outlines.",
    website: "https://circumicons.com",
    github: "https://github.com/klaufel/circum-icons",
    npm: "circum-icons",
    stars: 800,
    iconCount: 288,
    license: "MPL-2.0",
    frameworks: ["react", "vue", "svelte", "nextjs", "vanilla"],
    style: ["outline"],
    figmaPlugin: true,
    typescript: false,
    treeshakable: true,
    pros: ["Superb aesthetic consistency", "Rounded outlines look soft and modern", "MPL-2.0 open-source license"],
    cons: ["Small count of 288 icons", "Outline style only"],
    installCommand: "npm install circum-icons",
    usageExample: "import { Home } from 'circum-icons'\n\nexport default function App() {\n  return <Home size={24} />\n}"
  },
  {
    name: "Elusive Icons",
    slug: "elusive-icons",
    description: "A clean, customisable web font and SVG vector icon set optimized for Bootstrap layouts.",
    website: "https://redux.io/",
    github: "https://github.com/dovy/elusive-icons",
    npm: "elusive-icons",
    stars: 1200,
    iconCount: 304,
    license: "OFL-1.1",
    frameworks: ["react", "vue", "svelte", "nextjs", "vanilla"],
    style: ["solid"],
    figmaPlugin: true,
    typescript: false,
    treeshakable: true,
    pros: ["High contrast filled designs", "Bootstrap grid system native layout", "OFL-1.1 open source license"],
    cons: ["Slightly legacy visual look", "Solid weights only"],
    installCommand: "npm install elusive-icons",
    usageExample: "import 'elusive-icons/css/elusive-icons.min.css'\n\nexport default function App() {\n  return <i className='el el-home'></i>\n}"
  }
]

export function getIconBySlug(slug: string) {
  return icons.find((i) => i.slug === slug)
}

export function getComparisonPairs() {
  const pairs: [IconLibrary, IconLibrary][] = []
  for (let i = 0; i < icons.length; i++) {
    for (let j = i + 1; j < icons.length; j++) {
      pairs.push([icons[i], icons[j]])
    }
  }
  return pairs
}